apiVersion: v1
kind: Secret
metadata:
  name: livekit-blobstorage-secret
type: Opaque
stringData:
  AZURE_CONTAINER_NAME: "recordings"
  AZURE_STORAGE_ACCOUNT: "your azure storage account name"
  AZURE_STORAGE_KEY: "your azure storage key"
