apiVersion: v1
kind: Secret
metadata:
  name: livekit-agents-secrets
type: Opaque
stringData:
  LIVEKIT_URL: "livekit.xyzhub.pw"
  LIVEKIT_API_KEY: "${var.livekit_api_key}"
  LIVEKIT_API_SECRET: "${var.livekit_api_secret}"
