apiVersion: v1
kind: Secret
metadata:
  name: livekit-agents-secrets
type: Opaque
stringData:
  LIVEKIT_URL: "livekit2.xyzhub.pw"
  LIVEKIT_API_KEY: "YOUR_CUSTOM_API_KEY"
  LIVEKIT_API_SECRET: "YOUR_CUSTOM_API_SECRET"
