# .github/workflows/build-electron.yml
name: Build Electron App

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/electron-app/**'

jobs:
  build_electron:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install deps
        working-directory: apps/electron-app
        run: npm ci

      - name: Build Electron
        # ajusta la ruta/script si tu build está en otro lugar
        run: .\scripts\build-electron.ps1
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: electron-app
          path: |
            apps/electron-app/dist/**
