on:
  push:
    branches:
      - main

jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install deps
        working-directory: apps/api-functions
        run: npm ci

      - name: Run Prisma Migrations with SQL Admin
        working-directory: apps/api-functions
        env:
          PGHOST: livekit-agent-azure-postgres-server-flexible.postgres.database.azure.com
          PGUSER: livekitadmin@livekit-agent-azure-postgres-server-flexible
          PGPASSWORD: ${{ secrets.POSTGRES_ADMIN_PASSWORD }}
          PGDATABASE: postgres
          PGPORT: 5432
          PGSSLMODE: require
          # Construye DATABASE_URL escapando @ en el usuario:
          DATABASE_URL: >-
            postgresql://livekitadmin%40livekit-agent-azure-postgres-server-flexible:${{ secrets.POSTGRES_ADMIN_PASSWORD }}@livekit-agent-azure-postgres-server-flexible.postgres.database.azure.com:5432/postgres?schema=public&sslmode=require
        run: |
          # Verifica conexión rápida (opcional)
          npx prisma db pull
          npx prisma migrate deploy

      - name: Build TypeScript
        working-directory: apps/api-functions
        run: npm run build

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name:        ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package:         apps/api-functions
