name: Deploy API Functions with Prisma Migrations

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api-functions/**'
      - '.github/workflows/deploy-api-functions.yml'

permissions:
  contents: read
  id-token: write

jobs:
  deploy_api_functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies (root)
        run: npm ci

      - name: Run or Push Prisma Schema
        working-directory: apps/api-functions
        env:
          PGHOST: livekit-agent-azure-postgres-server-flexible.postgres.database.azure.com
          PGUSER: livekitadmin
          PGPASSWORD: ${{ secrets.POSTGRES_ADMIN_PASSWORD }}
          PGDATABASE: postgres
          PGPORT: 5432
          PGSSLMODE: require
          DATABASE_URL: >-
            postgresql://livekitadmin:${{ secrets.POSTGRES_ADMIN_PASSWORD }}@livekit-agent-azure-postgres-server-flexible.postgres.database.azure.com:5432/postgres?schema=public&sslmode=require
        run: |
          if [ -d prisma/migrations ] && [ "$(ls -A prisma/migrations)" ]; then
            echo "🔄 Migraciones encontradas, ejecutando prisma migrate deploy"
            npx prisma migrate deploy
          else
            echo "✨ No hay migraciones, haciendo prisma db push para crear tablas"
            npx prisma db push
          fi

      - name: Build API Functions (TypeScript)
        working-directory: apps/api-functions
        run: npm run build

      - name: Deploy API Functions to Azure
        uses: Azure/functions-action@v1
        with:
          app-name:        ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package:         apps/api-functions
