name: Deploy API Functions with Prisma Schema

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/api-functions/**'
      - '.github/workflows/deploy-api-functions.yml'

permissions:
  contents: read
  id-token: write

jobs:
  deploy_api_functions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: npm

      - name: Install deps & generate Prisma client
        working-directory: apps/api-functions
        run: |
          npm ci
          npx prisma generate

      - name: Apply database migrations
        working-directory: apps/api-functions
        env:
          DATABASE_URL: >-
            postgresql://livekitadmin:${{ secrets.POSTGRES_ADMIN_PASSWORD }}@livekit-agent-azure-postgres-server-flexible.postgres.database.azure.com:5432/livekit-agent-azure-db?schema=public&sslmode=require
        run: npx prisma migrate deploy

      - name: Build & prepare dist
        working-directory: apps/api-functions
        run: |
          npm run build
          npm run prepare-dist

      - name: Deploy API Functions to Azure
        uses: Azure/functions-action@v1
        with:
          app-name:        ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package:         apps/api-functions/dist
          remote-build:    true
