name: Deploy API Functions with Prisma Schema

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/api-functions/**'
      - '.github/workflows/deploy-api-functions.yml'

permissions:
  contents: read
  id-token: write

jobs:
  deploy_api_functions:
    runs-on: ubuntu-latest

    steps:
      # 1) Código
      - uses: actions/checkout@v4

      # 2) Node + caché npm
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: npm

      # 3) Instalar dependencias (no generamos cliente aquí)
      - name: Install dependencies
        working-directory: apps/api-functions
        run: npm ci


      # 5) Compilar, copiar artefactos y generar Prisma Client (ya con binary-targets correctos)
      - name: Build & prepare dist
        working-directory: apps/api-functions
        env:
          DATABASE_URL: >-
            postgresql://livekitadmin:${{ secrets.POSTGRES_ADMIN_PASSWORD }}@livekit-agent-azure-postgres-server-flexible.postgres.database.azure.com:5432/livekit-agent-azure-db?schema=public&sslmode=require
        run: |
          npm run build
          npm run prepare-dist     # copia node_modules, Prisma runtime, schema, etc.
          npm run prisma:deploy

      # 6) Despliegue a Azure Functions
      - name: Deploy API Functions to Azure
        uses: Azure/functions-action@v1
        with:
          app-name:        ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package:         apps/api-functions/dist
