name: Deploy API Functions with Prisma Schema

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api-functions/**'
      - '.github/workflows/deploy-api-functions.yml'

permissions:
  contents: read
  id-token: write

jobs:
  deploy_api_functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies (root)
        working-directory: apps/api-functions
        run: npm ci

      - name: Push Prisma schema and create tables
        working-directory: apps/api-functions
        env:
          DATABASE_URL: >-
            postgresql://livekitadmin:${{ secrets.POSTGRES_ADMIN_PASSWORD }}@livekit-agent-azure-postgres-server-flexible.postgres.database.azure.com:5432/livekit-agent-azure-db?schema=public&sslmode=require
        run: |
          echo "✨ Pushing Prisma schema to livekit-agent-azure-db…"
          npx prisma db push

      - name: Build & prepare dist
        working-directory: apps/api-functions
        run: npm run build && npm run prepare-dist:prod

      - name: Deploy API Functions to Azure
        uses: Azure/functions-action@v1
        with:
          app-name:        ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package:         apps/api-functions/dist
