name: Deploy Admin-Web to Azure Static Web Apps

# Trigger on any change under apps/admin-web on main branch
on:
  push:
    branches: [ main ]
    paths:
      - 'apps/admin-web/**'

jobs:
  deploy_admin_web:
    runs-on: ubuntu-latest

    # Pull in all Azure- and VITE_… secrets for use in every step
    env:
      # ——————————————————————————————————————————————
      # Azure OIDC authentication (no client secret stored in repo)
      # ——————————————————————————————————————————————
      AZURE_CLIENT_ID:        ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID:        ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # ——————————————————————————————————————————————
      # Application settings injected at Vite build time
      # ——————————————————————————————————————————————
      VITE_AZURE_AD_CLIENT_ID:               ${{ secrets.VITE_AZURE_AD_CLIENT_ID }}
      VITE_AZURE_AD_TENANT_ID:               ${{ secrets.VITE_AZURE_AD_TENANT_ID }}
      VITE_AZURE_AD_REDIRECT_URI:            ${{ secrets.VITE_AZURE_AD_REDIRECT_URI }}
      VITE_AZURE_AD_POST_LOGOUT_REDIRECT_URI: ${{ secrets.VITE_AZURE_AD_POST_LOGOUT_REDIRECT_URI }}
      VITE_AZURE_AD_API_CLIENT_ID:           ${{ secrets.VITE_AZURE_AD_API_CLIENT_ID }}
      VITE_AZURE_AD_API_SCOPE_URI:           ${{ secrets.VITE_AZURE_AD_API_SCOPE_URI }}
      VITE_API_URL:                          ${{ secrets.VITE_API_URL }}

    steps:
      # 1) Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Login to Azure via OIDC (no long-lived credentials needed)
      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          client-id:       ${{ env.AZURE_CLIENT_ID }}
          tenant-id:       ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      # 3) Install Node.js (and cache npm modules)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: npm

      # 4) Install deps & build your Vite app
      - name: Install dependencies & build
        working-directory: apps/admin-web
        run: |
          npm ci
          npm run build
        # VITE_… env vars are inherited from job-level env

      # 5) Deploy the static assets to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Token for your Static Web App (stored in GH Secrets)
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_APP_DEPLOY_KEY }}
          # A GitHub token for updating the PR status, etc.
          repo_token:                     ${{ secrets.PERSONAL_TOKEN }}
          action:                         upload
          app_location:                   apps/admin-web
          api_location:                   ''
          app_artifact_location:          dist
